services:
  - type: web
    name: habit-tracker-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: habit-tracker-backend
          property: port
    # Add your environment variables in Render dashboard:
    # SUPABASE_URL
    # SUPABASE_SERVICE_ROLE_KEY
    # CLIENT_URL